# Auto-generated formal skill module
SKILL_MODULE = {'skill_id': 'm_brick_clay_old',
 'skill_name': 'M_Brick_Clay_Old Formal Skill Module',
 'version': '1.0.0',
 'enabled': True,
 'generated_at': '2026-04-23 10:33:29',
 'material_path': '/Game/StarterContent/Materials/M_Brick_Clay_Old.M_Brick_Clay_Old',
 'description': 'AI-generated reusable material analysis skill module.',
 'applies_to': {'material_paths': ['/Game/StarterContent/Materials/M_Brick_Clay_Old.M_Brick_Clay_Old'],
                'material_names': ['M_Brick_Clay_Old'],
                'tags': ['game',
                         'startercontent',
                         'materials',
                         'm_brick_clay_old.m_brick_clay_old']},
 'rules': [{'rule_id': 'grayscale_packing_check',
            'rule_name': 'Grayscale_Packing_Check',
            'severity': 'medium',
            'trigger': '当材质中出现多个仅使用单通道的TextureSample节点时',
            'check_logic': '检查这些采样器的纹理用途是否均为噪声、遮罩或粗糙度等标量数据',
            'fix_strategy': '将这些纹理合并为一张RGBA纹理，并替换采样器节点'},
           {'rule_id': 'uv_logic_modularization',
            'rule_name': 'UV_Logic_Modularization',
            'severity': 'medium',
            'trigger': '当TexCoord节点后紧跟相同的Multiply或Add操作超过2次时',
            'check_logic': '对比各路径的计算模式是否一致',
            'fix_strategy': '创建Material Function，输入UV和Scale/Offset参数，输出计算后的UV'}]}
