# Auto-generated formal skill module
SKILL_MODULE = {'skill_id': 'm_water_ocean',
 'skill_name': 'M_Water_Ocean Formal Skill Module',
 'version': '1.0.0',
 'enabled': True,
 'generated_at': '2026-04-20 04:20:46',
 'material_path': '/Game/StarterContent/Materials/M_Water_Ocean.M_Water_Ocean',
 'description': 'AI-generated reusable material analysis skill module.',
 'applies_to': {'material_paths': ['/Game/StarterContent/Materials/M_Water_Ocean.M_Water_Ocean'],
                'material_names': ['M_Water_Ocean'],
                'tags': ['game', 'startercontent', 'materials', 'm_water_ocean.m_water_ocean']},
 'rules': [{'rule_id': 'texture_sampler_efficiency',
            'rule_name': 'Texture_Sampler_Efficiency',
            'severity': 'medium',
            'trigger': '当材质中存在多个仅使用单通道 (R/G/B/A) 的 Texture Sample 时',
            'check_logic': '遍历所有 Texture Sample 节点，统计其输出引脚的连接情况。',
            'fix_strategy': '建议美术师在 DCC 软件或引擎内将这些 Mask 图合并为一张多通道纹理。'},
           {'rule_id': 'vertex_shader_promotion',
            'rule_name': 'Vertex_Shader_Promotion',
            'severity': 'medium',
            'trigger': '当 WorldPosition 或 TextureCoordinate 节点后紧跟数学运算并输入到 Texture Sample 的 UV 引脚时',
            'check_logic': '检查 UV 链条中是否存在复杂的数学运算（Divide/Multiply/Add）。',
            'fix_strategy': '将该计算链条连接到主材质节点的 Customized UV 引脚。'}]}
